[package]
name = "calc"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false
description = "A simple expression evaluator demonstrating query-flow"

[dependencies]
query-flow.workspace = true

[dev-dependencies]
query-flow-inspector.workspace = true
